# Generated by Django 3.2.4 on 2021-08-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_alter_tareas_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('materia', models.TextField(verbose_name='Materia')),
                ('mensaje', models.TextField(verbose_name='Descripción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='tareas',
            name='actividad',
            field=models.TextField(max_length=100, null=True, verbose_name='Actividad'),
        ),
    ]
