# Generated by Django 3.2.4 on 2021-08-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20210825_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='biblioteca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.TextField(max_length=100, null=True, verbose_name='Nombre Editorial')),
                ('nombre', models.TextField(null=True, verbose_name='Nombre Libro')),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Biblioteca',
                'verbose_name_plural': 'Bibliotecas',
                'ordering': ['created'],
            },
        ),
    ]
